//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSclientC.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicePortBinding", Namespace="http://service_endpoint/")]
    public partial class ServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAOperationCompleted;
        
        private System.Threading.SendOrPostCallback setAOperationCompleted;
        
        private System.Threading.SendOrPostCallback remAOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSumAOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBOperationCompleted;
        
        private System.Threading.SendOrPostCallback setBOperationCompleted;
        
        private System.Threading.SendOrPostCallback remBOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPOperationCompleted;
        
        private System.Threading.SendOrPostCallback remPOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSOperationCompleted;
        
        private System.Threading.SendOrPostCallback setSOperationCompleted;
        
        private System.Threading.SendOrPostCallback remSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWOperationCompleted;
        
        private System.Threading.SendOrPostCallback setWOperationCompleted;
        
        private System.Threading.SendOrPostCallback remWOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceService() {
            this.Url = global::WSclientC.Properties.Settings.Default.WSclientC_localhost_ServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getACompletedEventHandler getACompleted;
        
        /// <remarks/>
        public event setACompletedEventHandler setACompleted;
        
        /// <remarks/>
        public event remACompletedEventHandler remACompleted;
        
        /// <remarks/>
        public event getSumACompletedEventHandler getSumACompleted;
        
        /// <remarks/>
        public event getBCompletedEventHandler getBCompleted;
        
        /// <remarks/>
        public event setBCompletedEventHandler setBCompleted;
        
        /// <remarks/>
        public event remBCompletedEventHandler remBCompleted;
        
        /// <remarks/>
        public event getPCompletedEventHandler getPCompleted;
        
        /// <remarks/>
        public event setPCompletedEventHandler setPCompleted;
        
        /// <remarks/>
        public event remPCompletedEventHandler remPCompleted;
        
        /// <remarks/>
        public event getSCompletedEventHandler getSCompleted;
        
        /// <remarks/>
        public event setSCompletedEventHandler setSCompleted;
        
        /// <remarks/>
        public event remSCompletedEventHandler remSCompleted;
        
        /// <remarks/>
        public event getWCompletedEventHandler getWCompleted;
        
        /// <remarks/>
        public event setWCompletedEventHandler setWCompleted;
        
        /// <remarks/>
        public event remWCompletedEventHandler remWCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public autoparts[] getA() {
            object[] results = this.Invoke("getA", new object[0]);
            return ((autoparts[])(results[0]));
        }
        
        /// <remarks/>
        public void getAAsync() {
            this.getAAsync(null);
        }
        
        /// <remarks/>
        public void getAAsync(object userState) {
            if ((this.getAOperationCompleted == null)) {
                this.getAOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAOperationCompleted);
            }
            this.InvokeAsync("getA", new object[0], this.getAOperationCompleted, userState);
        }
        
        private void OngetAOperationCompleted(object arg) {
            if ((this.getACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getACompleted(this, new getACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public autoparts[] setA([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] autoparts arg0) {
            object[] results = this.Invoke("setA", new object[] {
                        arg0});
            return ((autoparts[])(results[0]));
        }
        
        /// <remarks/>
        public void setAAsync(autoparts arg0) {
            this.setAAsync(arg0, null);
        }
        
        /// <remarks/>
        public void setAAsync(autoparts arg0, object userState) {
            if ((this.setAOperationCompleted == null)) {
                this.setAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetAOperationCompleted);
            }
            this.InvokeAsync("setA", new object[] {
                        arg0}, this.setAOperationCompleted, userState);
        }
        
        private void OnsetAOperationCompleted(object arg) {
            if ((this.setACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setACompleted(this, new setACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public autoparts[] remA([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0) {
            object[] results = this.Invoke("remA", new object[] {
                        arg0});
            return ((autoparts[])(results[0]));
        }
        
        /// <remarks/>
        public void remAAsync(int arg0) {
            this.remAAsync(arg0, null);
        }
        
        /// <remarks/>
        public void remAAsync(int arg0, object userState) {
            if ((this.remAOperationCompleted == null)) {
                this.remAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremAOperationCompleted);
            }
            this.InvokeAsync("remA", new object[] {
                        arg0}, this.remAOperationCompleted, userState);
        }
        
        private void OnremAOperationCompleted(object arg) {
            if ((this.remACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.remACompleted(this, new remACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getSumA() {
            object[] results = this.Invoke("getSumA", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getSumAAsync() {
            this.getSumAAsync(null);
        }
        
        /// <remarks/>
        public void getSumAAsync(object userState) {
            if ((this.getSumAOperationCompleted == null)) {
                this.getSumAOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSumAOperationCompleted);
            }
            this.InvokeAsync("getSumA", new object[0], this.getSumAOperationCompleted, userState);
        }
        
        private void OngetSumAOperationCompleted(object arg) {
            if ((this.getSumACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSumACompleted(this, new getSumACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public brands[] getB() {
            object[] results = this.Invoke("getB", new object[0]);
            return ((brands[])(results[0]));
        }
        
        /// <remarks/>
        public void getBAsync() {
            this.getBAsync(null);
        }
        
        /// <remarks/>
        public void getBAsync(object userState) {
            if ((this.getBOperationCompleted == null)) {
                this.getBOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBOperationCompleted);
            }
            this.InvokeAsync("getB", new object[0], this.getBOperationCompleted, userState);
        }
        
        private void OngetBOperationCompleted(object arg) {
            if ((this.getBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBCompleted(this, new getBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public brands[] setB([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] brands arg0) {
            object[] results = this.Invoke("setB", new object[] {
                        arg0});
            return ((brands[])(results[0]));
        }
        
        /// <remarks/>
        public void setBAsync(brands arg0) {
            this.setBAsync(arg0, null);
        }
        
        /// <remarks/>
        public void setBAsync(brands arg0, object userState) {
            if ((this.setBOperationCompleted == null)) {
                this.setBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetBOperationCompleted);
            }
            this.InvokeAsync("setB", new object[] {
                        arg0}, this.setBOperationCompleted, userState);
        }
        
        private void OnsetBOperationCompleted(object arg) {
            if ((this.setBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setBCompleted(this, new setBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public brands[] remB([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0) {
            object[] results = this.Invoke("remB", new object[] {
                        arg0});
            return ((brands[])(results[0]));
        }
        
        /// <remarks/>
        public void remBAsync(int arg0) {
            this.remBAsync(arg0, null);
        }
        
        /// <remarks/>
        public void remBAsync(int arg0, object userState) {
            if ((this.remBOperationCompleted == null)) {
                this.remBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremBOperationCompleted);
            }
            this.InvokeAsync("remB", new object[] {
                        arg0}, this.remBOperationCompleted, userState);
        }
        
        private void OnremBOperationCompleted(object arg) {
            if ((this.remBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.remBCompleted(this, new remBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public promotions[] getP() {
            object[] results = this.Invoke("getP", new object[0]);
            return ((promotions[])(results[0]));
        }
        
        /// <remarks/>
        public void getPAsync() {
            this.getPAsync(null);
        }
        
        /// <remarks/>
        public void getPAsync(object userState) {
            if ((this.getPOperationCompleted == null)) {
                this.getPOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPOperationCompleted);
            }
            this.InvokeAsync("getP", new object[0], this.getPOperationCompleted, userState);
        }
        
        private void OngetPOperationCompleted(object arg) {
            if ((this.getPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPCompleted(this, new getPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public promotions[] setP([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] promotions arg0) {
            object[] results = this.Invoke("setP", new object[] {
                        arg0});
            return ((promotions[])(results[0]));
        }
        
        /// <remarks/>
        public void setPAsync(promotions arg0) {
            this.setPAsync(arg0, null);
        }
        
        /// <remarks/>
        public void setPAsync(promotions arg0, object userState) {
            if ((this.setPOperationCompleted == null)) {
                this.setPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPOperationCompleted);
            }
            this.InvokeAsync("setP", new object[] {
                        arg0}, this.setPOperationCompleted, userState);
        }
        
        private void OnsetPOperationCompleted(object arg) {
            if ((this.setPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPCompleted(this, new setPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public promotions[] remP([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0) {
            object[] results = this.Invoke("remP", new object[] {
                        arg0});
            return ((promotions[])(results[0]));
        }
        
        /// <remarks/>
        public void remPAsync(int arg0) {
            this.remPAsync(arg0, null);
        }
        
        /// <remarks/>
        public void remPAsync(int arg0, object userState) {
            if ((this.remPOperationCompleted == null)) {
                this.remPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremPOperationCompleted);
            }
            this.InvokeAsync("remP", new object[] {
                        arg0}, this.remPOperationCompleted, userState);
        }
        
        private void OnremPOperationCompleted(object arg) {
            if ((this.remPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.remPCompleted(this, new remPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public suppliers[] getS() {
            object[] results = this.Invoke("getS", new object[0]);
            return ((suppliers[])(results[0]));
        }
        
        /// <remarks/>
        public void getSAsync() {
            this.getSAsync(null);
        }
        
        /// <remarks/>
        public void getSAsync(object userState) {
            if ((this.getSOperationCompleted == null)) {
                this.getSOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSOperationCompleted);
            }
            this.InvokeAsync("getS", new object[0], this.getSOperationCompleted, userState);
        }
        
        private void OngetSOperationCompleted(object arg) {
            if ((this.getSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSCompleted(this, new getSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public suppliers[] setS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] suppliers arg0) {
            object[] results = this.Invoke("setS", new object[] {
                        arg0});
            return ((suppliers[])(results[0]));
        }
        
        /// <remarks/>
        public void setSAsync(suppliers arg0) {
            this.setSAsync(arg0, null);
        }
        
        /// <remarks/>
        public void setSAsync(suppliers arg0, object userState) {
            if ((this.setSOperationCompleted == null)) {
                this.setSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetSOperationCompleted);
            }
            this.InvokeAsync("setS", new object[] {
                        arg0}, this.setSOperationCompleted, userState);
        }
        
        private void OnsetSOperationCompleted(object arg) {
            if ((this.setSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setSCompleted(this, new setSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public suppliers[] remS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0) {
            object[] results = this.Invoke("remS", new object[] {
                        arg0});
            return ((suppliers[])(results[0]));
        }
        
        /// <remarks/>
        public void remSAsync(int arg0) {
            this.remSAsync(arg0, null);
        }
        
        /// <remarks/>
        public void remSAsync(int arg0, object userState) {
            if ((this.remSOperationCompleted == null)) {
                this.remSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremSOperationCompleted);
            }
            this.InvokeAsync("remS", new object[] {
                        arg0}, this.remSOperationCompleted, userState);
        }
        
        private void OnremSOperationCompleted(object arg) {
            if ((this.remSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.remSCompleted(this, new remSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public warranty[] getW() {
            object[] results = this.Invoke("getW", new object[0]);
            return ((warranty[])(results[0]));
        }
        
        /// <remarks/>
        public void getWAsync() {
            this.getWAsync(null);
        }
        
        /// <remarks/>
        public void getWAsync(object userState) {
            if ((this.getWOperationCompleted == null)) {
                this.getWOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWOperationCompleted);
            }
            this.InvokeAsync("getW", new object[0], this.getWOperationCompleted, userState);
        }
        
        private void OngetWOperationCompleted(object arg) {
            if ((this.getWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWCompleted(this, new getWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public warranty[] setW([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] warranty arg0) {
            object[] results = this.Invoke("setW", new object[] {
                        arg0});
            return ((warranty[])(results[0]));
        }
        
        /// <remarks/>
        public void setWAsync(warranty arg0) {
            this.setWAsync(arg0, null);
        }
        
        /// <remarks/>
        public void setWAsync(warranty arg0, object userState) {
            if ((this.setWOperationCompleted == null)) {
                this.setWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetWOperationCompleted);
            }
            this.InvokeAsync("setW", new object[] {
                        arg0}, this.setWOperationCompleted, userState);
        }
        
        private void OnsetWOperationCompleted(object arg) {
            if ((this.setWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setWCompleted(this, new setWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service_endpoint/", ResponseNamespace="http://service_endpoint/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public warranty[] remW([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0) {
            object[] results = this.Invoke("remW", new object[] {
                        arg0});
            return ((warranty[])(results[0]));
        }
        
        /// <remarks/>
        public void remWAsync(int arg0) {
            this.remWAsync(arg0, null);
        }
        
        /// <remarks/>
        public void remWAsync(int arg0, object userState) {
            if ((this.remWOperationCompleted == null)) {
                this.remWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremWOperationCompleted);
            }
            this.InvokeAsync("remW", new object[] {
                        arg0}, this.remWOperationCompleted, userState);
        }
        
        private void OnremWOperationCompleted(object arg) {
            if ((this.remWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.remWCompleted(this, new remWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types/")]
    public partial class autoparts {
        
        private string brandField;
        
        private int idField;
        
        private int kolField;
        
        private string nameField;
        
        private double priceField;
        
        private string promotionField;
        
        private string supplieField;
        
        private string warrantyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int kol {
            get {
                return this.kolField;
            }
            set {
                this.kolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string promotion {
            get {
                return this.promotionField;
            }
            set {
                this.promotionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string supplie {
            get {
                return this.supplieField;
            }
            set {
                this.supplieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types/")]
    public partial class warranty {
        
        private int durationField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types/")]
    public partial class suppliers {
        
        private string addressField;
        
        private long innField;
        
        private string nameField;
        
        private long telephoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types/")]
    public partial class promotions {
        
        private string dataField;
        
        private int durationField;
        
        private string essenceField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string essence {
            get {
                return this.essenceField;
            }
            set {
                this.essenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types/")]
    public partial class brands {
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getACompletedEventHandler(object sender, getACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public autoparts[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((autoparts[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void setACompletedEventHandler(object sender, setACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public autoparts[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((autoparts[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void remACompletedEventHandler(object sender, remACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class remACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal remACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public autoparts[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((autoparts[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getSumACompletedEventHandler(object sender, getSumACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSumACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSumACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBCompletedEventHandler(object sender, getBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public brands[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((brands[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void setBCompletedEventHandler(object sender, setBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public brands[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((brands[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void remBCompletedEventHandler(object sender, remBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class remBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal remBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public brands[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((brands[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getPCompletedEventHandler(object sender, getPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public promotions[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((promotions[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void setPCompletedEventHandler(object sender, setPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public promotions[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((promotions[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void remPCompletedEventHandler(object sender, remPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class remPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal remPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public promotions[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((promotions[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getSCompletedEventHandler(object sender, getSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public suppliers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((suppliers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void setSCompletedEventHandler(object sender, setSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public suppliers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((suppliers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void remSCompletedEventHandler(object sender, remSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class remSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal remSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public suppliers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((suppliers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getWCompletedEventHandler(object sender, getWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public warranty[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((warranty[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void setWCompletedEventHandler(object sender, setWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public warranty[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((warranty[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void remWCompletedEventHandler(object sender, remWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class remWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal remWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public warranty[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((warranty[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591