
package service_endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.Autoparts;
import types.Brands;
import types.ListA;
import types.ListB;
import types.ListP;
import types.ListS;
import types.ListW;
import types.Promotions;
import types.Suppliers;
import types.Warranty;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Service", targetNamespace = "http://service_endpoint/")
@XmlSeeAlso({
    service_endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @return
     *     returns types.ListA
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getA", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetA")
    @ResponseWrapper(localName = "getAResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetAResponse")
    public ListA getA();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListA
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setA", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetA")
    @ResponseWrapper(localName = "setAResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetAResponse")
    public ListA setA(
        @WebParam(name = "arg0", targetNamespace = "")
        Autoparts arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListA
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remA", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemA")
    @ResponseWrapper(localName = "remAResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemAResponse")
    public ListA remA(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumA", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetSumA")
    @ResponseWrapper(localName = "getSumAResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetSumAResponse")
    public int getSumA();

    /**
     * 
     * @return
     *     returns types.ListB
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getB", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetB")
    @ResponseWrapper(localName = "getBResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetBResponse")
    public ListB getB();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListB
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setB", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetB")
    @ResponseWrapper(localName = "setBResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetBResponse")
    public ListB setB(
        @WebParam(name = "arg0", targetNamespace = "")
        Brands arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListB
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remB", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemB")
    @ResponseWrapper(localName = "remBResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemBResponse")
    public ListB remB(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns types.ListP
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getP", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetP")
    @ResponseWrapper(localName = "getPResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetPResponse")
    public ListP getP();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListP
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setP", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetP")
    @ResponseWrapper(localName = "setPResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetPResponse")
    public ListP setP(
        @WebParam(name = "arg0", targetNamespace = "")
        Promotions arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListP
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remP", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemP")
    @ResponseWrapper(localName = "remPResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemPResponse")
    public ListP remP(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns types.ListS
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getS", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetS")
    @ResponseWrapper(localName = "getSResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetSResponse")
    public ListS getS();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListS
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setS", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetS")
    @ResponseWrapper(localName = "setSResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetSResponse")
    public ListS setS(
        @WebParam(name = "arg0", targetNamespace = "")
        Suppliers arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListS
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remS", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemS")
    @ResponseWrapper(localName = "remSResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemSResponse")
    public ListS remS(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns types.ListW
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getW", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetW")
    @ResponseWrapper(localName = "getWResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.GetWResponse")
    public ListW getW();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListW
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setW", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetW")
    @ResponseWrapper(localName = "setWResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.SetWResponse")
    public ListW setW(
        @WebParam(name = "arg0", targetNamespace = "")
        Warranty arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListW
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remW", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemW")
    @ResponseWrapper(localName = "remWResponse", targetNamespace = "http://service_endpoint/", className = "service_endpoint.RemWResponse")
    public ListW remW(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
